### ISSUE TITLE
SQLite and json :).

### ISSUE THREAD

**Issue by KhArtNJava** [cindustries/unreal-sqlite3#1]
Hello.

In the past I am faced with question like how to integrate SQLite+Json in UE. But I haven't free time for that.

It could be interesting task for you, if you want.

It good to see, that project is still alive!

Regards, Khusnutdinov Arthur N.

**Comment by Getty** [comment]
I am confused, the string to put into the field can be of course generated from any other kind of note infrastructure, and again put back in, that is more a problem of Unreal Engine itself, then specific to the lib.
