### ISSUE TITLE
Getting an error when trying to include SQLiteDatabase.h in other C++ classes

### ISSUE THREAD

**Issue by flimshaw** [cindustries/unreal-sqlite3#4]
After following the instructions to install this lib, I get the prompt to build the library, and it builds properly.  I can see "SQLiteDatabase" in the list of classes when I create a new class in UE4.  But when I try to add "SQLiteDatabase.h" to other actors, I get an error that the library cannot be found.  Do I need to do something else in Visual Studio to enable other classes to see the SQLite library? 

Here is the compiler error:

`Severity Code    Description Project File    Line    Suppression State
Error   C1083   Cannot open include file: 'SQLiteDatabase.h': No such file or directory StarChamber_Alpha   F:\UnrealProjects\StarChamber\StarChamber_Alpha\Source\StarChamber_Alpha\ActiveStarRegistry.cpp 4`    

I'm currently just adding the include statement to some standard Actor boilerplate like so:

```
// Fill out your copyright notice in the Description page of Project Settings.

#include "StarChamber_Alpha.h"
#include "SQLiteDatabase.h"
#include "ActiveStarRegistry.h"


// Sets default values
AActiveStarRegistry::AActiveStarRegistry()
{
    // Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
    PrimaryActorTick.bCanEverTick = true;

}
```

Thanks a lot

**Comment by BastiaanGrisel** [comment]
I've struggled with this as well. What fixed it for me was to append `"CISQLite3"` to the `PublicDependencyModuleNames`in `Source/<project name>/<project name>.Build.cs` like this:
`PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "CISQLite3" });
`

**Comment by flimshaw** [comment]
Thank you so much, it's been a real struggle to just wrap my head around how UE4/C++ module management works, hard to find answers sometimes.

**Comment by Getty** [comment]
Yeah, without the public dependency the library will not be included at all, and so not the header files and so not the references needed for compiling. Blueprint structure is different and so you dont need to add it for usage in blueprint. I will close this then for now, sorry for the late reply, i .... somehow don't get emails for this project i just realized ;)
